/*
 * Web of Science API Lite
 * A responsive API that supports rich searching across the Web of Science Core Collection to retrieve core article metadata.  This service provides a great way to reuse Web of Science data both internally and externally to enhance  institutional repositories and research networking systems with best-in-class data. This API supports searching across the Web of Science to retrieve item-level metadata with limited fields:  - UT (Unique Identifier) - Authors - Author keywords - Document type - Title - Issue - Pages - Publication date - Source title - Volume - DOI - ISBN - ISSN   The API supports JSON and XML responses, and this documentation supports trying both response types. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clarivate.woslite.api;

import com.clarivate.woslite.ApiException;
import com.clarivate.woslite.models.WosLiteResponse;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for IntegrationApi
 */
@Ignore
public class IntegrationApiTest {

    private final IntegrationApi api = new IntegrationApi();

    
    /**
     * Find record(s) by specific id
     *
     * This operation returns a record identified by a unique identifier. You may specify multiple identifiers in a single request.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void idUniqueIdGetTest() throws ApiException {
        String databaseId = null;
        String uniqueId = null;
        Integer count = null;
        Integer firstRecord = null;
        String lang = null;
        String sortField = null;
        WosLiteResponse response = api.idUniqueIdGet(databaseId, uniqueId, count, firstRecord, lang, sortField);

        // TODO: test validations
    }
    
}
