/*
 * Web of Science API Lite
 * A responsive API that supports rich searching across the Web of Science Core Collection to retrieve core article metadata.  This service provides a great way to reuse Web of Science data both internally and externally to enhance  institutional repositories and research networking systems with best-in-class data. This API supports searching across the Web of Science to retrieve item-level metadata with limited fields:  - UT (Unique Identifier) - Authors - Author keywords - Document type - Title - Issue - Pages - Publication date - Source title - Volume - DOI - ISBN - ISSN   The API supports JSON and XML responses, and this documentation supports trying both response types. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clarivate.woslite.models;

import org.junit.Test;


/**
 * Model tests for Other
 */
public class OtherTest {
    private final Other model = new Other();

    /**
     * Model tests for Other
     */
    @Test
    public void testOther() {
        // TODO: test Other
    }

    /**
     * Test the property 'identifierEissn'
     */
    @Test
    public void identifierEissnTest() {
        // TODO: test identifierEissn
    }

    /**
     * Test the property 'contributorResearcherIDResearcherIDs'
     */
    @Test
    public void contributorResearcherIDResearcherIDsTest() {
        // TODO: test contributorResearcherIDResearcherIDs
    }

    /**
     * Test the property 'contributorResearcherIDNames'
     */
    @Test
    public void contributorResearcherIDNamesTest() {
        // TODO: test contributorResearcherIDNames
    }

    /**
     * Test the property 'identifierDoi'
     */
    @Test
    public void identifierDoiTest() {
        // TODO: test identifierDoi
    }

    /**
     * Test the property 'identifierIssn'
     */
    @Test
    public void identifierIssnTest() {
        // TODO: test identifierIssn
    }

    /**
     * Test the property 'identifierArticleNo'
     */
    @Test
    public void identifierArticleNoTest() {
        // TODO: test identifierArticleNo
    }

    /**
     * Test the property 'identifierIsbn'
     */
    @Test
    public void identifierIsbnTest() {
        // TODO: test identifierIsbn
    }

    /**
     * Test the property 'researcherIDDisclaimer'
     */
    @Test
    public void researcherIDDisclaimerTest() {
        // TODO: test researcherIDDisclaimer
    }

    /**
     * Test the property 'identifierXrefDoi'
     */
    @Test
    public void identifierXrefDoiTest() {
        // TODO: test identifierXrefDoi
    }

    /**
     * Test the property 'identifierIds'
     */
    @Test
    public void identifierIdsTest() {
        // TODO: test identifierIds
    }

}
