/*
 * Web of Science API Lite
 * A responsive API that supports rich searching across the Web of Science Core Collection to retrieve core article metadata.  This service provides a great way to reuse Web of Science data both internally and externally to enhance  institutional repositories and research networking systems with best-in-class data. This API supports searching across the Web of Science to retrieve item-level metadata with limited fields:  - UT (Unique Identifier) - Authors - Author keywords - Document type - Title - Issue - Pages - Publication date - Source title - Volume - DOI - ISBN - ISSN   The API supports JSON and XML responses, and this documentation supports trying both response types. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clarivate.woslite.models;

import org.junit.Test;


/**
 * Model tests for Source
 */
public class SourceTest {
    private final Source model = new Source();

    /**
     * Model tests for Source
     */
    @Test
    public void testSource() {
        // TODO: test Source
    }

    /**
     * Test the property 'pages'
     */
    @Test
    public void pagesTest() {
        // TODO: test pages
    }

    /**
     * Test the property 'sourceTitle'
     */
    @Test
    public void sourceTitleTest() {
        // TODO: test sourceTitle
    }

    /**
     * Test the property 'issue'
     */
    @Test
    public void issueTest() {
        // TODO: test issue
    }

    /**
     * Test the property 'volume'
     */
    @Test
    public void volumeTest() {
        // TODO: test volume
    }

    /**
     * Test the property 'specialIssue'
     */
    @Test
    public void specialIssueTest() {
        // TODO: test specialIssue
    }

    /**
     * Test the property 'bookSeriesTitle'
     */
    @Test
    public void bookSeriesTitleTest() {
        // TODO: test bookSeriesTitle
    }

    /**
     * Test the property 'publishedBiblioDate'
     */
    @Test
    public void publishedBiblioDateTest() {
        // TODO: test publishedBiblioDate
    }

    /**
     * Test the property 'publishedBiblioYear'
     */
    @Test
    public void publishedBiblioYearTest() {
        // TODO: test publishedBiblioYear
    }

}
