/*
 * Web of Science API Lite
 * A responsive API that supports rich searching across the Web of Science Core Collection to retrieve core article metadata.  This service provides a great way to reuse Web of Science data both internally and externally to enhance  institutional repositories and research networking systems with best-in-class data. This API supports searching across the Web of Science to retrieve item-level metadata with limited fields:  - UT (Unique Identifier) - Authors - Author keywords - Document type - Title - Issue - Pages - Publication date - Source title - Volume - DOI - ISBN - ISSN   The API supports JSON and XML responses, and this documentation supports trying both response types. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clarivate.woslite.models;

import org.junit.Test;


/**
 * Model tests for WosLiteRecord
 */
public class WosLiteRecordTest {
    private final WosLiteRecord model = new WosLiteRecord();

    /**
     * Model tests for WosLiteRecord
     */
    @Test
    public void testWosLiteRecord() {
        // TODO: test WosLiteRecord
    }

    /**
     * Test the property 'UT'
     */
    @Test
    public void UTTest() {
        // TODO: test UT
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'doctype'
     */
    @Test
    public void doctypeTest() {
        // TODO: test doctype
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'author'
     */
    @Test
    public void authorTest() {
        // TODO: test author
    }

    /**
     * Test the property 'keyword'
     */
    @Test
    public void keywordTest() {
        // TODO: test keyword
    }

    /**
     * Test the property 'other'
     */
    @Test
    public void otherTest() {
        // TODO: test other
    }

}
