/*
 * Web of Science API Lite
 * A responsive API that supports rich searching across the Web of Science Core Collection to retrieve core article metadata.  This service provides a great way to reuse Web of Science data both internally and externally to enhance  institutional repositories and research networking systems with best-in-class data. This API supports searching across the Web of Science to retrieve item-level metadata with limited fields:  - UT (Unique Identifier) - Authors - Author keywords - Document type - Title - Issue - Pages - Publication date - Source title - Volume - DOI - ISBN - ISSN   The API supports JSON and XML responses, and this documentation supports trying both response types. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clarivate.woslite.models;

import org.junit.Test;


/**
 * Model tests for WosLiteResponse
 */
public class WosLiteResponseTest {
    private final WosLiteResponse model = new WosLiteResponse();

    /**
     * Model tests for WosLiteResponse
     */
    @Test
    public void testWosLiteResponse() {
        // TODO: test WosLiteResponse
    }

    /**
     * Test the property 'queryResult'
     */
    @Test
    public void queryResultTest() {
        // TODO: test queryResult
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
