/*
 * Web of Science API Lite
 * A responsive API that supports rich searching across the Web of Science Core Collection to retrieve core article metadata.  This service provides a great way to reuse Web of Science data both internally and externally to enhance  institutional repositories and research networking systems with best-in-class data. This API supports searching across the Web of Science to retrieve item-level metadata with limited fields:  - UT (Unique Identifier) - Authors - Author keywords - Document type - Title - Issue - Pages - Publication date - Source title - Volume - DOI - ISBN - ISSN   The API supports JSON and XML responses, and this documentation supports trying both response types. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clarivate.woslite.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * The document types of record
 */
@ApiModel(description = "The document types of record")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-06-02T10:06:41.554+02:00[Europe/Berlin]")
public class Doctype {
  public static final String SERIALIZED_NAME_DOCTYPE = "Doctype";
  @SerializedName(SERIALIZED_NAME_DOCTYPE)
  private List<String> doctype = null;


  public Doctype doctype(List<String> doctype) {
    
    this.doctype = doctype;
    return this;
  }

  public Doctype addDoctypeItem(String doctypeItem) {
    if (this.doctype == null) {
      this.doctype = new ArrayList<String>();
    }
    this.doctype.add(doctypeItem);
    return this;
  }

   /**
   * Get doctype
   * @return doctype
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[\"Article\",\"Proceeding paper\"]", value = "")

  public List<String> getDoctype() {
    return doctype;
  }


  public void setDoctype(List<String> doctype) {
    this.doctype = doctype;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Doctype doctype = (Doctype) o;
    return Objects.equals(this.doctype, doctype.doctype);
  }

  @Override
  public int hashCode() {
    return Objects.hash(doctype);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Doctype {\n");
    sb.append("    doctype: ").append(toIndentedString(doctype)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

