/*
 * Web of Science API Lite
 * A responsive API that supports rich searching across the Web of Science Core Collection to retrieve core article metadata.  This service provides a great way to reuse Web of Science data both internally and externally to enhance  institutional repositories and research networking systems with best-in-class data. This API supports searching across the Web of Science to retrieve item-level metadata with limited fields:  - UT (Unique Identifier) - Authors - Author keywords - Document type - Title - Issue - Pages - Publication date - Source title - Volume - DOI - ISBN - ISSN   The API supports JSON and XML responses, and this documentation supports trying both response types. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clarivate.woslite.models;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * The source of this article; journal, book or medium in which the document was published
 */
@ApiModel(description = "The source of this article; journal, book or medium in which the document was published")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-06-02T10:06:41.554+02:00[Europe/Berlin]")
public class Other {
  public static final String SERIALIZED_NAME_IDENTIFIER_EISSN = "Identifier.Eissn";
  @SerializedName(SERIALIZED_NAME_IDENTIFIER_EISSN)
  private List<String> identifierEissn = null;

  public static final String SERIALIZED_NAME_CONTRIBUTOR_RESEARCHER_I_D_RESEARCHER_I_DS = "Contributor.ResearcherID.ResearcherIDs";
  @SerializedName(SERIALIZED_NAME_CONTRIBUTOR_RESEARCHER_I_D_RESEARCHER_I_DS)
  private List<String> contributorResearcherIDResearcherIDs = null;

  public static final String SERIALIZED_NAME_CONTRIBUTOR_RESEARCHER_I_D_NAMES = "Contributor.ResearcherID.Names";
  @SerializedName(SERIALIZED_NAME_CONTRIBUTOR_RESEARCHER_I_D_NAMES)
  private List<String> contributorResearcherIDNames = null;

  public static final String SERIALIZED_NAME_IDENTIFIER_DOI = "Identifier.Doi";
  @SerializedName(SERIALIZED_NAME_IDENTIFIER_DOI)
  private List<String> identifierDoi = null;

  public static final String SERIALIZED_NAME_IDENTIFIER_ISSN = "Identifier.Issn";
  @SerializedName(SERIALIZED_NAME_IDENTIFIER_ISSN)
  private List<String> identifierIssn = null;

  public static final String SERIALIZED_NAME_IDENTIFIER_ARTICLE_NO = "Identifier.article_no";
  @SerializedName(SERIALIZED_NAME_IDENTIFIER_ARTICLE_NO)
  private List<String> identifierArticleNo = null;

  public static final String SERIALIZED_NAME_IDENTIFIER_ISBN = "Identifier.Isbn";
  @SerializedName(SERIALIZED_NAME_IDENTIFIER_ISBN)
  private List<String> identifierIsbn = null;

  /**
   * Gets or Sets researcherIDDisclaimer
   */
  @JsonAdapter(ResearcherIDDisclaimerEnum.Adapter.class)
  public enum ResearcherIDDisclaimerEnum {
    RESEARCHERID_DATA_PROVIDED_BY_CLARIVATE_ANALYTICS("ResearcherID data provided by Clarivate Analytics");

    private String value;

    ResearcherIDDisclaimerEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ResearcherIDDisclaimerEnum fromValue(String value) {
      for (ResearcherIDDisclaimerEnum b : ResearcherIDDisclaimerEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ResearcherIDDisclaimerEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ResearcherIDDisclaimerEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ResearcherIDDisclaimerEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ResearcherIDDisclaimerEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_RESEARCHER_I_D_DISCLAIMER = "ResearcherID.Disclaimer";
  @SerializedName(SERIALIZED_NAME_RESEARCHER_I_D_DISCLAIMER)
  private List<ResearcherIDDisclaimerEnum> researcherIDDisclaimer = null;

  public static final String SERIALIZED_NAME_IDENTIFIER_XREF_DOI = "Identifier.Xref_Doi";
  @SerializedName(SERIALIZED_NAME_IDENTIFIER_XREF_DOI)
  private List<String> identifierXrefDoi = null;

  public static final String SERIALIZED_NAME_IDENTIFIER_IDS = "Identifier.Ids";
  @SerializedName(SERIALIZED_NAME_IDENTIFIER_IDS)
  private List<String> identifierIds = null;


  public Other identifierEissn(List<String> identifierEissn) {
    
    this.identifierEissn = identifierEissn;
    return this;
  }

  public Other addIdentifierEissnItem(String identifierEissnItem) {
    if (this.identifierEissn == null) {
      this.identifierEissn = new ArrayList<String>();
    }
    this.identifierEissn.add(identifierEissnItem);
    return this;
  }

   /**
   * Electronic International Standard Identifier Number. [What is an ISSN?](https://www.issn.org/understanding-the-issn/what-is-an-issn/)
   * @return identifierEissn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Electronic International Standard Identifier Number. [What is an ISSN?](https://www.issn.org/understanding-the-issn/what-is-an-issn/)")

  public List<String> getIdentifierEissn() {
    return identifierEissn;
  }


  public void setIdentifierEissn(List<String> identifierEissn) {
    this.identifierEissn = identifierEissn;
  }


  public Other contributorResearcherIDResearcherIDs(List<String> contributorResearcherIDResearcherIDs) {
    
    this.contributorResearcherIDResearcherIDs = contributorResearcherIDResearcherIDs;
    return this;
  }

  public Other addContributorResearcherIDResearcherIDsItem(String contributorResearcherIDResearcherIDsItem) {
    if (this.contributorResearcherIDResearcherIDs == null) {
      this.contributorResearcherIDResearcherIDs = new ArrayList<String>();
    }
    this.contributorResearcherIDResearcherIDs.add(contributorResearcherIDResearcherIDsItem);
    return this;
  }

   /**
   * ResearcherID provided from Web of Science. [What is my Web of Science ResearcherID?](https://publons.freshdesk.com/support/solutions/articles/12000038281-what-is-my-web-of-science-researcherid-)
   * @return contributorResearcherIDResearcherIDs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ResearcherID provided from Web of Science. [What is my Web of Science ResearcherID?](https://publons.freshdesk.com/support/solutions/articles/12000038281-what-is-my-web-of-science-researcherid-)")

  public List<String> getContributorResearcherIDResearcherIDs() {
    return contributorResearcherIDResearcherIDs;
  }


  public void setContributorResearcherIDResearcherIDs(List<String> contributorResearcherIDResearcherIDs) {
    this.contributorResearcherIDResearcherIDs = contributorResearcherIDResearcherIDs;
  }


  public Other contributorResearcherIDNames(List<String> contributorResearcherIDNames) {
    
    this.contributorResearcherIDNames = contributorResearcherIDNames;
    return this;
  }

  public Other addContributorResearcherIDNamesItem(String contributorResearcherIDNamesItem) {
    if (this.contributorResearcherIDNames == null) {
      this.contributorResearcherIDNames = new ArrayList<String>();
    }
    this.contributorResearcherIDNames.add(contributorResearcherIDNamesItem);
    return this;
  }

   /**
   * The author names in the same order from &#x60;Contributor.ResearcherID.ResearcherIDs&#x60;
   * @return contributorResearcherIDNames
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The author names in the same order from `Contributor.ResearcherID.ResearcherIDs`")

  public List<String> getContributorResearcherIDNames() {
    return contributorResearcherIDNames;
  }


  public void setContributorResearcherIDNames(List<String> contributorResearcherIDNames) {
    this.contributorResearcherIDNames = contributorResearcherIDNames;
  }


  public Other identifierDoi(List<String> identifierDoi) {
    
    this.identifierDoi = identifierDoi;
    return this;
  }

  public Other addIdentifierDoiItem(String identifierDoiItem) {
    if (this.identifierDoi == null) {
      this.identifierDoi = new ArrayList<String>();
    }
    this.identifierDoi.add(identifierDoiItem);
    return this;
  }

   /**
   * Digital Object Identifier
   * @return identifierDoi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Digital Object Identifier")

  public List<String> getIdentifierDoi() {
    return identifierDoi;
  }


  public void setIdentifierDoi(List<String> identifierDoi) {
    this.identifierDoi = identifierDoi;
  }


  public Other identifierIssn(List<String> identifierIssn) {
    
    this.identifierIssn = identifierIssn;
    return this;
  }

  public Other addIdentifierIssnItem(String identifierIssnItem) {
    if (this.identifierIssn == null) {
      this.identifierIssn = new ArrayList<String>();
    }
    this.identifierIssn.add(identifierIssnItem);
    return this;
  }

   /**
   * International Standard Identifier Number. [What is an ISSN?](https://www.issn.org/understanding-the-issn/what-is-an-issn/)
   * @return identifierIssn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "International Standard Identifier Number. [What is an ISSN?](https://www.issn.org/understanding-the-issn/what-is-an-issn/)")

  public List<String> getIdentifierIssn() {
    return identifierIssn;
  }


  public void setIdentifierIssn(List<String> identifierIssn) {
    this.identifierIssn = identifierIssn;
  }


  public Other identifierArticleNo(List<String> identifierArticleNo) {
    
    this.identifierArticleNo = identifierArticleNo;
    return this;
  }

  public Other addIdentifierArticleNoItem(String identifierArticleNoItem) {
    if (this.identifierArticleNo == null) {
      this.identifierArticleNo = new ArrayList<String>();
    }
    this.identifierArticleNo.add(identifierArticleNoItem);
    return this;
  }

   /**
   * Article Number
   * @return identifierArticleNo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Article Number")

  public List<String> getIdentifierArticleNo() {
    return identifierArticleNo;
  }


  public void setIdentifierArticleNo(List<String> identifierArticleNo) {
    this.identifierArticleNo = identifierArticleNo;
  }


  public Other identifierIsbn(List<String> identifierIsbn) {
    
    this.identifierIsbn = identifierIsbn;
    return this;
  }

  public Other addIdentifierIsbnItem(String identifierIsbnItem) {
    if (this.identifierIsbn == null) {
      this.identifierIsbn = new ArrayList<String>();
    }
    this.identifierIsbn.add(identifierIsbnItem);
    return this;
  }

   /**
   * International Standard Book Number. [What is an ISBN?](https://www.isbn-international.org/content/what-isbn)
   * @return identifierIsbn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "International Standard Book Number. [What is an ISBN?](https://www.isbn-international.org/content/what-isbn)")

  public List<String> getIdentifierIsbn() {
    return identifierIsbn;
  }


  public void setIdentifierIsbn(List<String> identifierIsbn) {
    this.identifierIsbn = identifierIsbn;
  }


  public Other researcherIDDisclaimer(List<ResearcherIDDisclaimerEnum> researcherIDDisclaimer) {
    
    this.researcherIDDisclaimer = researcherIDDisclaimer;
    return this;
  }

  public Other addResearcherIDDisclaimerItem(ResearcherIDDisclaimerEnum researcherIDDisclaimerItem) {
    if (this.researcherIDDisclaimer == null) {
      this.researcherIDDisclaimer = new ArrayList<ResearcherIDDisclaimerEnum>();
    }
    this.researcherIDDisclaimer.add(researcherIDDisclaimerItem);
    return this;
  }

   /**
   * Dislaimer for ResearcherID
   * @return researcherIDDisclaimer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Dislaimer for ResearcherID")

  public List<ResearcherIDDisclaimerEnum> getResearcherIDDisclaimer() {
    return researcherIDDisclaimer;
  }


  public void setResearcherIDDisclaimer(List<ResearcherIDDisclaimerEnum> researcherIDDisclaimer) {
    this.researcherIDDisclaimer = researcherIDDisclaimer;
  }


  public Other identifierXrefDoi(List<String> identifierXrefDoi) {
    
    this.identifierXrefDoi = identifierXrefDoi;
    return this;
  }

  public Other addIdentifierXrefDoiItem(String identifierXrefDoiItem) {
    if (this.identifierXrefDoi == null) {
      this.identifierXrefDoi = new ArrayList<String>();
    }
    this.identifierXrefDoi.add(identifierXrefDoiItem);
    return this;
  }

   /**
   * Digital Object Identifier
   * @return identifierXrefDoi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Digital Object Identifier")

  public List<String> getIdentifierXrefDoi() {
    return identifierXrefDoi;
  }


  public void setIdentifierXrefDoi(List<String> identifierXrefDoi) {
    this.identifierXrefDoi = identifierXrefDoi;
  }


  public Other identifierIds(List<String> identifierIds) {
    
    this.identifierIds = identifierIds;
    return this;
  }

  public Other addIdentifierIdsItem(String identifierIdsItem) {
    if (this.identifierIds == null) {
      this.identifierIds = new ArrayList<String>();
    }
    this.identifierIds.add(identifierIdsItem);
    return this;
  }

   /**
   * The IDS Number is included in the export from Web of Science to Researcher Solutions products. The ISI Document Delivery Number is used to uniquely identify documents that can be delivered via IDS. It is of no particular use if the user does not wish to use our document delivery.
   * @return identifierIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The IDS Number is included in the export from Web of Science to Researcher Solutions products. The ISI Document Delivery Number is used to uniquely identify documents that can be delivered via IDS. It is of no particular use if the user does not wish to use our document delivery.")

  public List<String> getIdentifierIds() {
    return identifierIds;
  }


  public void setIdentifierIds(List<String> identifierIds) {
    this.identifierIds = identifierIds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Other other = (Other) o;
    return Objects.equals(this.identifierEissn, other.identifierEissn) &&
        Objects.equals(this.contributorResearcherIDResearcherIDs, other.contributorResearcherIDResearcherIDs) &&
        Objects.equals(this.contributorResearcherIDNames, other.contributorResearcherIDNames) &&
        Objects.equals(this.identifierDoi, other.identifierDoi) &&
        Objects.equals(this.identifierIssn, other.identifierIssn) &&
        Objects.equals(this.identifierArticleNo, other.identifierArticleNo) &&
        Objects.equals(this.identifierIsbn, other.identifierIsbn) &&
        Objects.equals(this.researcherIDDisclaimer, other.researcherIDDisclaimer) &&
        Objects.equals(this.identifierXrefDoi, other.identifierXrefDoi) &&
        Objects.equals(this.identifierIds, other.identifierIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identifierEissn, contributorResearcherIDResearcherIDs, contributorResearcherIDNames, identifierDoi, identifierIssn, identifierArticleNo, identifierIsbn, researcherIDDisclaimer, identifierXrefDoi, identifierIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Other {\n");
    sb.append("    identifierEissn: ").append(toIndentedString(identifierEissn)).append("\n");
    sb.append("    contributorResearcherIDResearcherIDs: ").append(toIndentedString(contributorResearcherIDResearcherIDs)).append("\n");
    sb.append("    contributorResearcherIDNames: ").append(toIndentedString(contributorResearcherIDNames)).append("\n");
    sb.append("    identifierDoi: ").append(toIndentedString(identifierDoi)).append("\n");
    sb.append("    identifierIssn: ").append(toIndentedString(identifierIssn)).append("\n");
    sb.append("    identifierArticleNo: ").append(toIndentedString(identifierArticleNo)).append("\n");
    sb.append("    identifierIsbn: ").append(toIndentedString(identifierIsbn)).append("\n");
    sb.append("    researcherIDDisclaimer: ").append(toIndentedString(researcherIDDisclaimer)).append("\n");
    sb.append("    identifierXrefDoi: ").append(toIndentedString(identifierXrefDoi)).append("\n");
    sb.append("    identifierIds: ").append(toIndentedString(identifierIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

