/*
 * Web of Science API Lite
 * A responsive API that supports rich searching across the Web of Science Core Collection to retrieve core article metadata.  This service provides a great way to reuse Web of Science data both internally and externally to enhance  institutional repositories and research networking systems with best-in-class data. This API supports searching across the Web of Science to retrieve item-level metadata with limited fields:  - UT (Unique Identifier) - Authors - Author keywords - Document type - Title - Issue - Pages - Publication date - Source title - Volume - DOI - ISBN - ISSN   The API supports JSON and XML responses, and this documentation supports trying both response types. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clarivate.woslite.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * WosLiteResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-06-02T10:06:41.554+02:00[Europe/Berlin]")
public class WosLiteResponse {
  public static final String SERIALIZED_NAME_QUERY_RESULT = "QueryResult";
  @SerializedName(SERIALIZED_NAME_QUERY_RESULT)
  private QueryResult queryResult;

  public static final String SERIALIZED_NAME_DATA = "Data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private List<WosLiteRecord> data = null;


  public WosLiteResponse queryResult(QueryResult queryResult) {
    
    this.queryResult = queryResult;
    return this;
  }

   /**
   * Get queryResult
   * @return queryResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public QueryResult getQueryResult() {
    return queryResult;
  }


  public void setQueryResult(QueryResult queryResult) {
    this.queryResult = queryResult;
  }


  public WosLiteResponse data(List<WosLiteRecord> data) {
    
    this.data = data;
    return this;
  }

  public WosLiteResponse addDataItem(WosLiteRecord dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<WosLiteRecord>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * The array of the Web of Science records
   * @return data
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The array of the Web of Science records")

  public List<WosLiteRecord> getData() {
    return data;
  }


  public void setData(List<WosLiteRecord> data) {
    this.data = data;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WosLiteResponse wosLiteResponse = (WosLiteResponse) o;
    return Objects.equals(this.queryResult, wosLiteResponse.queryResult) &&
        Objects.equals(this.data, wosLiteResponse.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(queryResult, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WosLiteResponse {\n");
    sb.append("    queryResult: ").append(toIndentedString(queryResult)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

