/*
 * Web of Science API Lite
 * A responsive API that supports rich searching across the Web of Science Core Collection to retrieve core article metadata.  This service provides a great way to reuse Web of Science data both internally and externally to enhance  institutional repositories and research networking systems with best-in-class data. This API supports searching across the Web of Science to retrieve item-level metadata with limited fields:  - UT (Unique Identifier) - Authors - Author keywords - Document type - Title - Issue - Pages - Publication date - Source title - Volume - DOI - ISBN - ISSN   The API supports JSON and XML responses, and this documentation supports trying both response types. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clarivate.woslite.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * WosLiteRecord
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-06-02T10:06:41.554+02:00[Europe/Berlin]")
public class WosLiteRecord {
  public static final String SERIALIZED_NAME_U_T = "UT";
  @SerializedName(SERIALIZED_NAME_U_T)
  private String UT;

  public static final String SERIALIZED_NAME_TITLE = "Title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private WosLiteRecordTitle title;

  public static final String SERIALIZED_NAME_DOCTYPE = "Doctype";
  @SerializedName(SERIALIZED_NAME_DOCTYPE)
  private Doctype doctype;

  public static final String SERIALIZED_NAME_SOURCE = "Source";
  @SerializedName(SERIALIZED_NAME_SOURCE)
  private Source source;

  public static final String SERIALIZED_NAME_AUTHOR = "Author";
  @SerializedName(SERIALIZED_NAME_AUTHOR)
  private Author author;

  public static final String SERIALIZED_NAME_KEYWORD = "Keyword";
  @SerializedName(SERIALIZED_NAME_KEYWORD)
  private Keyword keyword;

  public static final String SERIALIZED_NAME_OTHER = "Other";
  @SerializedName(SERIALIZED_NAME_OTHER)
  private Other other;


  public WosLiteRecord UT(String UT) {
    
    this.UT = UT;
    return this;
  }

   /**
   * The unique identifier of Web of Science Record
   * @return UT
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "WOS:000454864800008", value = "The unique identifier of Web of Science Record")

  public String getUT() {
    return UT;
  }


  public void setUT(String UT) {
    this.UT = UT;
  }


  public WosLiteRecord title(WosLiteRecordTitle title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public WosLiteRecordTitle getTitle() {
    return title;
  }


  public void setTitle(WosLiteRecordTitle title) {
    this.title = title;
  }


  public WosLiteRecord doctype(Doctype doctype) {
    
    this.doctype = doctype;
    return this;
  }

   /**
   * Get doctype
   * @return doctype
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Doctype getDoctype() {
    return doctype;
  }


  public void setDoctype(Doctype doctype) {
    this.doctype = doctype;
  }


  public WosLiteRecord source(Source source) {
    
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Source getSource() {
    return source;
  }


  public void setSource(Source source) {
    this.source = source;
  }


  public WosLiteRecord author(Author author) {
    
    this.author = author;
    return this;
  }

   /**
   * Get author
   * @return author
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Author getAuthor() {
    return author;
  }


  public void setAuthor(Author author) {
    this.author = author;
  }


  public WosLiteRecord keyword(Keyword keyword) {
    
    this.keyword = keyword;
    return this;
  }

   /**
   * Get keyword
   * @return keyword
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Keyword getKeyword() {
    return keyword;
  }


  public void setKeyword(Keyword keyword) {
    this.keyword = keyword;
  }


  public WosLiteRecord other(Other other) {
    
    this.other = other;
    return this;
  }

   /**
   * Get other
   * @return other
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Other getOther() {
    return other;
  }


  public void setOther(Other other) {
    this.other = other;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WosLiteRecord wosLiteRecord = (WosLiteRecord) o;
    return Objects.equals(this.UT, wosLiteRecord.UT) &&
        Objects.equals(this.title, wosLiteRecord.title) &&
        Objects.equals(this.doctype, wosLiteRecord.doctype) &&
        Objects.equals(this.source, wosLiteRecord.source) &&
        Objects.equals(this.author, wosLiteRecord.author) &&
        Objects.equals(this.keyword, wosLiteRecord.keyword) &&
        Objects.equals(this.other, wosLiteRecord.other);
  }

  @Override
  public int hashCode() {
    return Objects.hash(UT, title, doctype, source, author, keyword, other);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WosLiteRecord {\n");
    sb.append("    UT: ").append(toIndentedString(UT)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    doctype: ").append(toIndentedString(doctype)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    keyword: ").append(toIndentedString(keyword)).append("\n");
    sb.append("    other: ").append(toIndentedString(other)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

